local c = require 'neon.colors'
local config = require 'neon.config'

local M = {}

M.base = {
  -- Styles
  Bold = { style = 'bold' },
  Italic = { style = 'italic' },
  Underlined = { style = 'underline' },

  Boolean = { fg = c.orange },
  Character = { fg = c.green },
  ColorColumn = { bg = c.dark },
  Comment = { fg = c.gray, style = 'italic' },
  Conceal = { fg = c.accent, bg = config.transparent_background and c.none or c.bg },
  Conditional = { fg = c.purple },
  Constant = { fg = c.orange },
  Cursor = { fg = c.cursor_fg, bg = c.cursor_bg },
  CursorColumn = { bg = c.dark },
  CursorIM = { fg = c.cursor_fg, bg = c.cursor_bg },
  CursorLine = { bg = c.dark },
  CursorLineNr = { fg = c.gray3, style = 'bold' },
  Debug = { fg = c.red },
  Define = { fg = c.purple },
  Delimiter = { fg = c.fg },
  DiffAdd = { fg = c.dark, bg = c.diff_add },
  DiffAdded = { fg = c.diff_add },
  DiffChange = { fg = c.dark, bg = c.diff_change, style = 'underline' },
  DiffDelete = { fg = c.dark, bg = c.diff_delete },
  DiffRemoved = { fg = c.diff_delete },
  DiffText = { fg = c.dark, bg = c.diff_text },
  DiffFile = { fg = c.cyan2 },
  DiffIndexLine = { fg = c.gray },
  Directory = { fg = c.blue3 },
  EndOfBuffer = { fg = c.bg },
  Error = { fg = c.red1, bg = c.bg, style = 'bold' },
  ErrorMsg = { fg = c.red1, bg = c.bg, style = 'bold' },
  Exception = { fg = c.purple },
  Float = { fg = c.orange },
  FloatBorder = { fg = c.gray, bg = c.dark },
  FoldColumn = { fg = c.accent, bg = c.dark },
  Folded = { fg = c.accent, bg = c.dark },
  Function = { fg = c.blue3 },
  Identifier = { fg = c.fg },
  Ignore = { fg = c.cyan2, bg = c.bg, style = 'bold' },
  IncSearch = { fg = c.gray3, bg = c.blue9 },
  Include = { fg = c.purple },
  Keyword = { fg = c.yellow2 },
  Label = { fg = c.blue3 },
  LineNr = { fg = c.gray2 },
  Macro = { fg = c.purple },
  MatchParen = { fg = c.blue3, bg = c.bg, style = 'underline' },
  MatchParenCur = { style = 'underline' },
  MatchWord = { style = 'underline' },
  MatchWordCur = { style = 'underline' },
  ModeMsg = { fg = c.fg, bg = c.bg },
  MoreMsg = { fg = c.orange },
  MsgArea = { fg = c.fg, bg = config.transparent_background and c.none or c.bg },
  MsgSeparator = { fg = c.fg, bg = c.bg },
  NonText = { fg = c.gray2 },
  Normal = { fg = c.fg, bg = config.transparent_background and c.none or c.bg },
  NormalFloat = { bg = c.gray1 },
  NormalNC = { fg = c.fg, bg = config.transparent_background and c.none or c.bg },
  Number = { fg = c.gray },
  Operator = { fg = c.purple },
  Pmenu = { fg = c.fg, bg = c.gray1},
  PmenuSbar = { bg = c.dark },
  PmenuSel = { fg = c.yellow3, bg = c.cursor_fg },
  PmenuThumb = { bg = c.gray },
  PreCondit = { fg = c.purple },
  PreProc = { fg = c.purple },
  Question = { fg = c.orange },
  QuickFixLine = { bg = c.gray1 },
  Repeat = { fg = c.purple },
  Search = { fg = c.gray3, bg = c.blue9 },
  SignColumn = { bg = c.bg },
  Special = { fg = c.purple },
  SpecialChar = { fg = c.fg },
  SpecialComment = { fg = c.gray },
  SpecialKey = { fg = c.blue3, style = 'bold' },
  SpellBad = { fg = c.red1, style = 'underline' },
  SpellCap = { fg = c.yellow2, style = 'underline' },
  SpellLocal = { fg = c.green, style = 'underline' },
  SpellRare = { fg = c.purple, style = 'underline' },
  Statement = { fg = c.purple },
  StatusLine = { fg = c.dark },
  StatusLineNC = { fg = c.dark },
  StatusLineSeparator = { fg = c.dark },
  StatusLineTerm = { fg = c.dark },
  StatusLineTermNC = { fg = c.dark },
  StorageClass = { fg = c.cyan2 },
  String = { fg = c.green },
  Structure = { fg = c.purple },
  Substitute = { fg = c.gray3, bg = c.brown },
  TabLine = { fg = c.gray3, bg = c.dark },
  TabLineFill = { fg = c.fg, bg = c.dark },
  TabLineSel = { fg = c.fg, bg = c.dark },
  Tag = { fg = c.blue3 },
  TermCursor = { fg = c.cursor_fg, bg = c.cursor_bg },
  TermCursorNC = { fg = c.cursor_fg, bg = c.cursor_bg },
  Title = { fg = c.blue3, style = 'bold' },
  Todo = { fg = c.red, bg = c.bg, style = 'bold' },
  Type = { fg = c.yellow2 },
  Typedef = { fg = c.purple },
  Variable = { fg = c.cyan2 },
  VertSplit = { fg = c.bg, bg = c.dark },
  Visual = { bg = c.blue2 },
  VisualNOS = { bg = c.dark },
  WarningMsg = { fg = c.red1, bg = c.bg },
  Whitespace = { fg = c.gray },
  WildMenu = { fg = c.dark, bg = c.blue3 },
  lCursor = { fg = c.cursor_fg, bg = c.cursor_bg },
  -- Markdown
  markdownBlockquote = { fg = c.accent },
  markdownBold = { fg = c.yellow2, style = 'bold' },
  markdownCode = { fg = c.green },
  markdownCodeBlock = { fg = c.green },
  markdownCodeDelimiter = { fg = c.green },
  markdownH1 = { fg = c.blue3 },
  markdownH2 = { fg = c.blue3 },
  markdownH3 = { fg = c.blue3 },
  markdownH4 = { fg = c.blue3 },
  markdownH5 = { fg = c.blue3 },
  markdownH6 = { fg = c.blue3 },
  markdownHeadingDelimiter = { fg = c.blue3 },
  markdownHeadingRule = { fg = c.accent },
  markdownId = { fg = c.purple },
  markdownIdDeclaration = { fg = c.blue3 },
  markdownIdDelimiter = { fg = c.gray3 },
  markdownItalic = { style = 'italic' },
  markdownLinkDelimiter = { fg = c.gray3 },
  markdownLinkText = { fg = c.blue3 },
  markdownListMarker = { fg = c.red },
  markdownOrderedListMarker = { fg = c.red },
  markdownRule = { fg = c.accent },
  markdownUrl = { fg = c.cyan2, style = 'underline' },
    -- NeoVim
  healthError = { fg = c.red1 },
  healthSuccess = { fg = c.green },
  healthWarning = { fg = c.orange2 },
}

M.plugins = {
  -- Cmp
  CmpDocumentation = { fg = c.fg, bg = c.none },
  CmpDocumentationBorder = { fg = c.gray, bg = c.none },
  CmpItemAbbr = { fg = c.fg, bg = c.none },
  CmpItemAbbrDeprecated = { fg = c.gray, bg = c.none },
  CmpItemAbbrMatch = { fg = c.yellow3, bg = c.none },
  CmpItemAbbrMatchFuzzy = { fg = c.yellow3, bg = c.none },
  CmpItemKind = { fg = c.blue3, bg = c.none },
  CmpItemMenu = { fg = c.gray3, bg = c.none },

  CmpItemKindDefault = { fg = c.dark, bg = c.none },
  CmpItemKindKeyword = { fg = c.cyan, bg = c.none },
  CmpItemKindVariable = { fg = c.magenta, bg = c.none },
  CmpItemKindConstant = { fg = c.magenta, bg = c.none },
  CmpItemKindReference = { fg = c.magenta, bg = c.none },
  CmpItemKindValue = { fg = c.magenta, bg = c.none },

  CmpItemKindFunction = { fg = c.blue, bg = c.none },
  CmpItemKindMethod = { fg = c.blue, bg = c.none },
  CmpItemKindConstructor = { fg = c.blue, bg = c.none },

  CmpItemKindClass = { fg = c.orange, bg = c.none },
  CmpItemKindInterface = { fg = c.orange, bg = c.none },
  CmpItemKindStruct = { fg = c.orange, bg = c.none },
  CmpItemKindEvent = { fg = c.orange, bg = c.none },
  CmpItemKindEnum = { fg = c.orange, bg = c.none },
  CmpItemKindUnit = { fg = c.orange, bg = c.none },

  CmpItemKindModule = { fg = c.yellow, bg = c.none },

  CmpItemKindProperty = { fg = c.green1, bg = c.none },
  CmpItemKindField = { fg = c.green1, bg = c.none },
  CmpItemKindTypeParameter = { fg = c.green1, bg = c.none },
  CmpItemKindEnumMember = { fg = c.green1, bg = c.none },
  CmpItemKindOperator = { fg = c.green1, bg = c.none },
  CmpItemKindSnippet = { fg = c.dark4, bg = c.none },
  -- Dashboard
  DashboardCenter = { fg = c.yellow2 },
  DashboardFooter = { fg = c.yellow1 },
  DashboardHeader = { fg = c.blue3 },
  -- Lsp
  DiagnosticError = { fg = c.red1 },
  DiagnosticHint = { fg = c.cyan2 },
  DiagnosticInfo = { fg = c.blue3 },
  DiagnosticWarn = { fg = c.yellow },
  DiagnosticFloatingError = { fg = c.red1 },
  DiagnosticFloatingHint = { fg = c.cyan2 },
  DiagnosticFloatingInfo = { fg = c.blue3 },
  DiagnosticFloatingWarn = { fg = c.yellow },
  DiagnosticSignError = { fg = c.red1 },
  DiagnosticSignHint = { fg = c.cyan2 },
  DiagnosticSignInfo = { fg = c.blue3 },
  DiagnosticSignWarn = { fg = c.yellow },
  DiagnosticUnderlineError = { style = 'underline' },
  DiagnosticUnderlineHint = { style = 'underline' },
  DiagnosticUnderlineInfo = { style = 'underline' },
  DiagnosticUnderlineWarn = { style = 'underline' },
  LspDiagnosticsDefaultError = { fg = c.red1 },
  LspDiagnosticsDefaultHint = { fg = c.cyan2 },
  LspDiagnosticsDefaultInformation = { fg = c.blue3 },
  LspDiagnosticsDefaultWarning = { fg = c.yellow },
  LspDiagnosticsError = { fg = c.red1 },
  LspDiagnosticsFloatingError = { fg = c.red1 },
  LspDiagnosticsFloatingHint = { fg = c.cyan2 },
  LspDiagnosticsFloatingInformation = { fg = c.blue3 },
  LspDiagnosticsFloatingWarning = { fg = c.yellow },
  LspDiagnosticsHint = { fg = c.cyan2 },
  LspDiagnosticsInformation = { fg = c.blue3 },
  LspDiagnosticsSignError = { fg = c.red1 },
  LspDiagnosticsSignHint = { fg = c.cyan2 },
  LspDiagnosticsSignInformation = { fg = c.blue3 },
  LspDiagnosticsSignWarning = { fg = c.yellow },
  LspDiagnosticsUnderlineError = { style = 'underline' },
  LspDiagnosticsUnderlineHint = { style = 'underline' },
  LspDiagnosticsUnderlineInformation = { style = 'underline' },
  LspDiagnosticsUnderlineWarning = { style = 'underline' },
  LspDiagnosticsVirtualTextError = { fg = c.red1 },
  LspDiagnosticsVirtualTextHint = { fg = c.cyan2 },
  LspDiagnosticsVirtualTextInformation = { fg = c.blue3 },
  LspDiagnosticsVirtualTextWarning = { fg = c.yellow },
  LspDiagnosticsWarning = { fg = c.yellow },
  LspReferenceRead = { bg = c.bg, style = 'bold' },
  LspReferenceText = { bg = c.bg, style = 'bold' },
  LspReferenceWrite = { bg = c.bg, style = 'bold' },
  -- GitSigns
  GitSignsAdd = { fg = c.diff_add },
  GitSignsChange = { fg = c.diff_change },
  GitSignsDelete = { fg = c.diff_delete },
  -- Nvim-tree
  NvimTreeCursorLine = { bg = c.bg },
  NvimTreeExecFile = { fg = c.fg },
  NvimTreeFolderIcon = { fg = c.yellow2 },
  NvimTreeFolderName = { fg = c.fg },
  NvimTreeEmptyFolderName = { fg = c.fg },
  NvimTreeIndentMarker = { fg = c.gray },
  NvimTreeImageFile = { fg = c.fg },
  NvimTreeNormal = { fg = c.accent, bg = c.dark },
  NvimTreeGitDeleted = { fg = c.fg },
  NvimTreeGitDirty = { fg = c.fg },
  NvimTreeGitMerge = { fg = c.fg },
  NvimTreeGitNew = { fg = c.fg },
  NvimTreeGitRenamed = { fg = c.fg },
  NvimTreeGitStaged = { fg = c.fg },
  NvimTreeOpenedFolderName = { fg = c.fg , style = 'italic' },
  NvimTreeRootFolder = { fg = c.gray, style = 'bold' },
  NvimTreeSpecialFile = { fg = c.orange },
  NvimTreeSymlink = { fg = c.gray3 },
  NvimTreeVertSplit = { fg = c.gray1 },
  -- Telescope
  TelescopeBorder = { fg = c.gray, bg = config.transparent_background and c.none or c.bg },
  TelescopeMatching = { fg = c.red1, style = 'bold' },
  TelescopePromptPrefix = { fg = c.gray },
  TelescopeSelection = { fg = c.yellow3, style = 'bold' },
  -- Treesitter
  TSAnnotation = { fg = c.red2 },
  TSAttribute = { fg = c.red2 },
  TSBoolean = { fg = c.blue3 },
  TSCharacter = { fg = c. cyan2 },
  TSComment = { fg = c.gray },
  TSConditional = { fg = c.fg },
  TSConstBuiltin = { fg = c.red1 },
  TSConstMacro = { fg = c.cyan2 },
  TSConstant = { fg = c.blue8 },
  TSConstructor = { fg = c.cyan2 },
  TSEmphasis = { style = 'italic' },
  TSError = { fg = c.red1 },
  TSException = { fg = c.red1 },
  TSField = { fg = c.yellow1 },
  TSFloat = { fg = c.green3 },
  TSFuncBuiltin = { fg = c.yellow2 },
  TSFuncMacro = { fg = c.yellow2 },
  TSFunction = { fg = c.yellow2 },
  TSInclude = { fg = c.red1 },
  TSKeyword = { fg = c.red1 },
  TSKeywordFunction = { fg = c.blue3 },
  TSKeywordOperator = { fg = c.red1 },
  TSKeywordReturn = { fg = c.red1 },
  TSLabel = { fg = c.blue8 },
  TSLiteral = { fg = c.orange },
  TSMethod = { fg = c.green4 },
  TSNamespace = { fg = c.cyan2 },
  TSNumber = { fg = c.blue4 },
  TSOperator = { fg = c.fg },
  TSParameter = { fg = c.blue4 },
  TSParameterReference = { fg = c.blue8 },
  TSProperty = { fg = c.blue8 },
  TSPunctBracket = { fg = c.fg },
  TSPunctDelimiter = { fg = c.fg },
  TSPunctSpecial = { fg = c.fg },
  TSQueryLinterError = { fg = c.orange2 },
  TSRepeat = { fg = c.red1 },
  TSString = { fg = c.cyan2 },
  TSStringEscape = { fg = c.cyan2 },
  TSStringRegex = { fg = c.cyan2 },
  TSStrong = { fg = c.orange },
  TSStructure = { fg = c.blue8 },
  TSSymbol = { fg = c.blue8 },
  TSTag = { fg = c.blue3 },
  TSTagDelimiter = { fg = c.gray },
  TSText = { fg = c.fg },
  TSTitle = { fg = c.blue3, style = 'bold' },
  TSType = { fg = c.blue3 },
  TSTypeBuiltin = { fg = c.red1 },
  TSURI = { fg = c.orange, style = 'underline' },
  TSUnderline = { style = 'underline' },
  TSVariable = { fg = c.yellow3 },
  TSVariableBuiltin = { fg = c.red1 },
  --  WhichKey
  WhichKey = { fg = c.red },
  WhichKeyGroup = { fg = c.yellow2 },
  WhichKeyDesc = { fg = c.fg },
  WhichKeySeperator = { fg = c.fg },
  WhichKeySeparator = { fg = c.fg },
  WhichKeyFloat = { fg = c.fg },
  WhichKeyValue = { fg = c.fg },
}

return M
